################################################################################
# https://github.com/zeke/semantic-pull-requests
################################################################################
titleAndCommits: true
allowMergeCommits: true
